### ISSUE TITLE
lack of utilities for manual operation

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/ansible-role-example#113]
##### ISSUE TYPE

 - Feature Idea
 
##### ROLE VERSION

```
N/A
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

manual operation is needed sometimes and some utilities like zsh and tmux are not installed
in the servers.
##### STEPS TO REPRODUCE

  zsh
  tmux

```yaml
N/A
```

```
zsh: not found
tmux: not found
```

##### EXPECTED RESULTS

zsh, tmux, etc. are installed
##### ACTUAL RESULTS

zsh, tmux, etc. are not installed

**Comment by trombik** [comment]
`ansible-role-zsh`, `ansible-role-tmux`, and `ansible-role-vim` have been released.
