### ISSUE TITLE
no document describing how to configure github repository

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/ansible-role-example#46]
setting ACL and protecting branches, etc.

**Comment by trombik** [comment]
Do you mean this is not enough or the procedures should be documented in a file?
 
https://github.com/reallyenglish/ansible-role-example/blob/master/docs/Rules.md#rules

**Comment by trombik** [comment]
the procedure for projects is documented at https://github.com/reallyenglish/ansible-project-example/blob/master/docs/Procedures/Managing_ACL.md

**Comment by mitsururike** [comment]
reference to the Procedures/Managing_ACL.md is necessary for ACL if it is to be followed.

**Comment by mitsururike** [comment]
I missed it.

**Comment by trombik** [comment]
do you think we need better navigation?

**Comment by mitsururike** [comment]
i think it is better if we had one.
create a role with qansible init -> write/commit the first implementation -> create a repo on github with some configurations -> git push -> (workflow cycle)
