### ISSUE TITLE
create standard rubocop.yml

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#60]
as proposed in [an issue](https://github.com/reallyenglish/ansible-role-example/issues/58), we will introduce `rubocop` to enforce and unify the style in ruby code. the default style will be used as a staring point.

as we fix `.rubocop_todo.yml`, there would be needs for discussions. if you need one, leave comments here.

**Comment by trombik** [comment]
which string literal should be used? I used to prefer single, but has switched to double because:

* you do not have to think when typing
* i do not use single or double quotes in strings, back tick just works in almost all cases except required by external constraints 
 
https://github.com/bbatsov/ruby-style-guide#consistent-string-literals

i'm all ears. if people think otherwise, let be it.

**Comment by mitsururike** [comment]
i'd like to know what the dev team is using.

**Comment by trombik** [comment]
unfortunately, cannot find one

**Comment by trombik** [comment]
what is suitable value for `Max` of `Metrics/LineLength`? the default is 80. when a line needs more length, what should be done?

**Comment by mitsururike** [comment]
could you show me the examples which really need 80+ lines?

**Comment by mitsururike** [comment]
for complex regexps, https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#regular-expressions might be useful.

**Comment by trombik** [comment]
@mitsururike URL, regex and file path?

**Comment by trombik** [comment]
> could you show me the examples which really need 80+ lines?

another question is, when you _have to_ violate rules, what should be done?

**Comment by mitsururike** [comment]
- i would use multi line string for strings and 'x' modifier for regexps.
- if you have a good reason to violate a rule, the rule should be revised.

**Comment by trombik** [comment]
do you mean `rubocop:disable` must not be used?

**Comment by mitsururike** [comment]
'revise' includes disabling a rule.

**Comment by trombik** [comment]
`rubocop:disable` may be used. when? what should be done with the `rubocop:disable`? after disabling it, what should the author do? i need a rule, rather than a policy statement.

**Comment by mitsururike** [comment]
i do not know the case that rubocop:disable is really necessary.
i would like to avoid disabling a rule if you do not have the actual case.

**Comment by trombik** [comment]
[there are many](https://searchcode.com/?q=rubocop%3Adisable) and it is the first rule you should create when introducing any style guide to a project. it is called as a guide, but rather, I prefer calling it an agreement. `rubocop` is way more complex than `style(7)` or the traditional KNF.

**Comment by trombik** [comment]
off the top of my head, method length is a typical one. you know long method is bad, but splitting one into many, and writing tests for each, takes time. another, some ruby-based configuration files tends to be long, such as `.gemspec`, and `Vagrantfile`.

**Comment by mitsururike** [comment]
this argument about DSLs is convincing.
http://stackoverflow.com/questions/40934345/rubocop-25-line-block-size-and-rspec-tests?answertab=votes#tab-top

**Comment by mitsururike** [comment]
I accept most of the default rules except the block size rule in DSL.
My candidate .ruboco.yml is
```yaml
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
```
How about adding rules and reason to a candidate .rubocop.yml and discuss?

**Comment by trombik** [comment]
here is my RFC
https://gist.github.com/trombik/68970cc0e014c5690a3acace37e06818

I will be testing existing roles. after the discussion, `qansible` will be updated

**Comment by mitsururike** [comment]
Could you add comments describing reasons and (if there are any) references to arguments or discussion which support the rules?

**Comment by trombik** [comment]
.rubocop.yml has been merged.

https://github.com/trombik/qansible/blob/master/lib/qansible/commands/init/templates/rubocop.yml
