### ISSUE TITLE
no document describes adding labels to repositories

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/ansible-role-example#66]
Some labels described in Procedures/Triaging_Issue are not in the default labels and you need to add them. Colors should be specified as well.

**Comment by trombik** [comment]
what color number should be used for each label? will document it.

**Comment by mitsururike** [comment]
any color is acceptable for me.
if you are interested in Color Universal Design, see
http://jfly.iam.u-tokyo.ac.jp/colorset/
